#是否启用物品打开菜单  使用物品会打开到菜主界面你可以在Main.yml中配置
MenuItemSwitcher: true
#如果启用了物品打开菜单,这里的设置才会生效
MenuItemID: "264:0"  #[菜单物品的ID(数字:特殊值 和 字符串ID(NK原版不支持))]
MenuItemName: "快捷菜单"  #[菜单物品的名称]
MenuItemIsEnchanting: false  #[菜单物品是否附魔]
MenuItemIsDrop: false  #[菜单物品是否允许丢弃]
MenuItemCheckTime: 30  #[检测玩家菜单间隔(时间s)]
#这里是EconomyAPI中货币的名称
MoneyName: "金币"

# 这里提供了菜单按钮的固定配置类型，您喜欢想要哪一种按钮就直接写在新建的菜单页面下即可,是对Main.yml的说明与解释
# type> 1(普通执行指令类型) 2(玩家输入类型) 3(玩家选择类型) 4(玩家整数滑动条类型) 5(玩家确定或取消类型)
# %p是玩家变量 %i是玩家输入的内容/选择的内容/滑条的整数(仅type2、type3、type4时生效),这两个变量仅在cmd中生效
Button1:
 type: 1 #普通执行指令类型 按钮
 name: "点我执行指令"
 texture: "textures/ui/filledStar.png"  #填写 无 时,不加载按钮贴图,如填写,贴图路径为本地材质路径
 money: 0  #填写 0 时,按下按钮不会对玩家进行Economy金钱检测,如不为0,会判断玩家是否拥有该数量的金币,最终扣除该数量的金币
 cmd: #执行指令 扣除金币
  - "givemoney %p 100@op"  #op为控制台命令,player为玩家执行指令
  - "say 我刚才按下了一个菜单按键!@player"
 permission: "true" #向指定权限的玩家展示这个按钮 填写权限节点名   默认所有人时 true
Button2:
 type: 2 #玩家输入类型 按钮
 name: "点我输入并执行指令"
 texture: "无"  #填写 无 时,不加载按钮贴图,如填写,贴图路径为本地材质路径
 tip: "请输入内容" #玩家输入栏提示
 text: "请您输入内容!" #玩家输入栏内提示
 money: 0  #填写 0 时,按下按钮不会对玩家进行Economy金钱检测,如不为0,会判断玩家是否拥有该数量的金币,最终扣除该数量的金币
 cmd: #执行指令 扣除金币
  - "givemoney %p 100@op"  #op为控制台命令,player为玩家执行指令
  - "say 我刚才输入了%i@player"
 permission: "true" #向指定权限的玩家展示这个按钮 填写权限节点名   默认所有人时 true
Button3:
 type: 3 #玩家选择类型 按钮
 name: "点我选择并执行指令"
 texture: "无"  #填写 无 时,不加载按钮贴图,如填写,贴图路径为本地材质路径
 tip: "请通过选项来选择内容" #玩家选择栏描述
 list:  #玩家选择栏选项
  - "选项a"
  - "选项n"
 money: 0  #填写 0 时,按下按钮不会对玩家进行Economy金钱检测,如不为0,会判断玩家是否拥有该数量的金币,最终扣除该数量的金币
 cmd: #执行指令 扣除金币
  - "givemoney %p 100@op"  #op为控制台命令,player为玩家执行指令
  - "say 我刚才选择了%i@player"
 permission: "true" #向指定权限的玩家展示这个按钮 填写权限节点名   默认所有人时 true
Button4:
 type: 4 #玩家滑条类型 按钮
 name: "点我滑动选择并执行指令"
 texture: "无"  #填写 无 时,不加载按钮贴图,如填写,贴图路径为本地材质路径
 tip: "请通过滑动来选择内容" #玩家滑动栏描述
 min: 1 #滑动栏的最小整数
 max: 10 #滑动栏的最大整数
 money: 0  #填写 0 时,按下按钮不会对玩家进行Economy金钱检测,如不为0,会判断玩家是否拥有该数量的金币,最终扣除该数量的金币
 cmd: #执行指令 扣除金币
  - "givemoney %p %i@op"  #op为控制台命令,player为玩家执行指令
  - "say 我刚才滑动选择了并给了自己金币:%i@player"
 permission: "true" #向指定权限的玩家展示这个按钮 填写权限节点名   默认所有人时 true
Button5:
 type: 5 #玩家确定或取消类型 按钮
 name: "点我确定或取消执行指令"
 texture: "无"  #填写 无 时,不加载按钮贴图,如填写,贴图路径为本地材质路径
 tip: "你要确定还是取消呢?点击下方的按钮做出你的决定吧!" #玩家确定或取消 内容描述
 money: 0  #填写 0 时,按下按钮不会对玩家进行Economy金钱检测,如不为0,会判断玩家是否拥有该数量的金币
 cmd: #玩家按下 确定 时执行的指令 扣除金币
   - "givemoney %p 100@op"  #op为控制台命令,player为玩家执行指令
 permission: "true" #向指定权限的玩家展示这个按钮 填写权限节点名   默认所有人时 true


